
# n = input()
# c = input()
# d = input()
# b = input()
# print(c, d, b, sep=n)
# a = int(input())
# b = int(input())
# print('Квадрат суммы', a, 'и', b, 'равен', (a+b)**2)
# print('Сумма квадратов', a, 'и', b, 'равна', a**2+b**2)
a = int(input())
b = str(a)+str(a)
c = str(a)+str(a)+str(a)
d = a+int(b)+int(c)
print(d)